replicaCount: 1

image:
  repository: simple-api
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

app:
  message: "Hello from Simple API (Helm)"
  environment: "local"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
